// IconHandler.idl: IconHandler 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 生成类型库(IconHandler.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";
[
	object,
	uuid(73a6ffaa-7865-4621-a6e1-cfc1afe2234a),
	pointer_default(unique)
]
interface IIconHandlerClient : IUnknown
{
};
[
	uuid(ca2e03cb-83ba-40e6-bf6f-48d7463abff4),
	version(1.0),
]
library IconHandlerLib
{
	importlib("stdole2.tlb");
	[
		uuid(00a7f0d3-6740-4a38-b1ee-20d811f70612)
	]
	coclass IconHandlerClient
	{
		[default] interface IIconHandlerClient;
		interface IPersistFile;
		interface IExtractIcon;
	};
};

import "shobjidl.idl";
