CREATE OR REPLACE PROCEDURE _MATLAB_取列名和类型 (表名 VARCHAR(32)) COMMENT '输入表名，覆盖创建一个临时表`_MATLAB_列名和类型`，包含COLUMN_NAME和COLUMN_TYPE两列，指示输入表名所有的列名称和完整类型' NOT DETERMINISTIC READS SQL DATA SQL SECURITY INVOKER
BEGIN
CREATE OR REPLACE TEMPORARY TABLE _MATLAB_列名和类型 AS
SELECT
	COLUMN_NAME,
	COLUMN_TYPE
FROM
	information_schema.COLUMNS
WHERE
	TABLE_SCHEMA = DATABASE ()
	AND TABLE_NAME = 表名;

IF NOT EXISTS (
	SELECT
		1
	FROM
		_MATLAB_列名和类型
	LIMIT
		1
) THEN
SET
	@`动态语句` = CONCAT(
		'CREATE OR REPLACE TABLE _MATLAB_列名和类型 AS SELECT * FROM ',
		输入表名,
		' LIMIT 1'
	);

PREPARE 语句准备
FROM
	@`动态语句`;

EXECUTE 语句准备;

CREATE OR REPLACE TEMPORARY TABLE _MATLAB_列名和类型 AS
SELECT
	COLUMN_NAME,
	COLUMN_TYPE
FROM
	information_schema.COLUMNS
WHERE
	TABLE_SCHEMA = DATABASE ()
	AND TABLE_NAME = '_MATLAB_列名和类型';

END IF;

END