CREATE OR REPLACE FUNCTION `_MATLAB_Blob转Double` (`Blob` TINYBLOB) RETURNS DOUBLE COMMENT '输入一个8字节BLOB，将其重新解释为DOUBLE值' DETERMINISTIC NO SQL SQL SECURITY INVOKER
BEGIN DECLARE 整数 BIGINT UNSIGNED;

SET
	整数 = CONV(HEX(REVERSE(`Blob`)), 16, 10);

RETURN (1 - (整数 >> 63) * 2) * ((整数 & (1 << 52) -1) / (1 << 52) + 1) * POWER(
	2,
	CAST(整数 >> 52 & (1 << 11) -1 AS SIGNED) - CAST(1 << 10 AS SIGNED) + 1
);

END