classdef FILEOP_FLAGS<uint16
	enumeration
		%指定多个目标文件（一一对应每个源文件）；而不是一个目录（存入所有源文件）。
		FOF_MULTIDESTFILES(0x0001)
		%不要显示进度对话框。
		FOF_SILENT(0x0004)
		%如果目标名称的文件已在目的地存在，请给移动、复制或重命名操作中的文件以新名称。
		FOF_RENAMEONCOLLISION(0x0008)
		%对于显示的任何对话框，请以“是”响应。
		FOF_NOCONFIRMATION(0x0010)
		%如果可能，保留撤消信息。如果源文件参数不包含完全合格的路径和文件名称，则忽略此标志。使用此旗帜可指示应将删除的文件移动到回收站，而不是彻底删除。
		FOF_ALLOWUNDO(0x0040)
		%仅在指定通配符文件名称的文件（不在文件夹上）上执行操作。
		FOF_FILESONLY(0x0080)
		%操作中，显示进度对话框，但不显示单独的文件名。
		FOF_SIMPLEPROGRESS(0x0100)
		%如果操作需要创建新目录，请不要要求用户确认新目录的创建。
		FOF_NOCONFIRMMKDIR(0x0200)
		%如果出现错误，不要向用户显示对话框。
		FOF_NOERRORUI(0x0400)
		%不要复制文件的安全属性。目标文件接收其新文件夹的安全属性。
		FOF_NOCOPYSECURITYATTRIBS(0x0800)
		%仅在本地目录中执行操作。不要递归到子目录（这是默认行为）。
		FOF_NORECURSION(0x1000)
		%不要将已连接的文件作为一个组移动。仅移动指定文件。
		FOF_NO_CONNECTED_ELEMENTS(0x2000)
		%如果文件在删除操作中永久销毁，而不是回收，请发送警告。这面旗帜部分覆盖FOF_NOCONFIRMATION。
		FOF_WANTNUKEWARNING(0x4000)
		%默默执行操作，不向用户呈现UI。这相当于FOF_SILENT+FOF_NOCONFIRMATION+FOF_NOERRORUI+FOF_NOCONFIRMMKDIR
		FOF_NO_UI(0x0614)
	end
end