DROP FUNCTION IF EXISTS _MATLAB_版本;
DROP FUNCTION IF EXISTS _MATLAB_表存在;
DROP PROCEDURE IF EXISTS _MATLAB_反序列化;
DROP FUNCTION IF EXISTS _MATLAB_Blob转Double;
DROP FUNCTION IF EXISTS _MATLAB_Blob转Float;
DROP FUNCTION IF EXISTS _MATLAB_Blob转Point;
DROP TABLE IF EXISTS _MATLAB_类型;